const ACCESS_TOKEN_KEY = "accessToken";

const HTTP_STATUS = {
  UNAUTHORIZED: 401,
} as const;

const TABLE_PAGE_SIZE: number = 20;

const MIN_LOADING_DURATION_MS = 500;
const PRODUCTS_LIST_REFETCH_INTERVAL_MS = 30_000;

const STALE_TIME_MS = 5 * 60 * 1000

export {
  ACCESS_TOKEN_KEY,
  HTTP_STATUS,
  TABLE_PAGE_SIZE,
  MIN_LOADING_DURATION_MS,
  PRODUCTS_LIST_REFETCH_INTERVAL_MS,
  STALE_TIME_MS
};
